/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DTO.BeneficiarioDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author Arturo ITSON
 */
public class frmAdministrarAbonos extends javax.swing.JFrame {

    /**
     * Creates new form frmAdministrarAbonos
     */
    
    BeneficiarioDTO beneficiario;
    
    public frmAdministrarAbonos(BeneficiarioDTO beneficiario) {
        initComponents();
        
        this.beneficiario = beneficiario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        campoTextoMonto = new javax.swing.JTextField();
        jblMonto = new javax.swing.JLabel();
        jblParcialidades = new javax.swing.JLabel();
        jblRestante = new javax.swing.JLabel();
        jblFecha = new javax.swing.JLabel();
        campoTextoRestante = new javax.swing.JTextField();
        campoTextoFecha = new javax.swing.JTextField();
        campoTextoParcialidades = new javax.swing.JTextField();
        btnRealizarAbono = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPagos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrar Abonos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnRegresar.setBackground(new java.awt.Color(23, 154, 249));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        campoTextoMonto.setBackground(new java.awt.Color(255, 255, 255));
        campoTextoMonto.setForeground(new java.awt.Color(0, 0, 0));
        campoTextoMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jblMonto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblMonto.setForeground(new java.awt.Color(0, 0, 0));
        jblMonto.setText("Monto");

        jblParcialidades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblParcialidades.setForeground(new java.awt.Color(0, 0, 0));
        jblParcialidades.setText("No. Parcialidades");

        jblRestante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblRestante.setForeground(new java.awt.Color(0, 0, 0));
        jblRestante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblRestante.setText("Restante");

        jblFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblFecha.setForeground(new java.awt.Color(0, 0, 0));
        jblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblFecha.setText("Fecha Hora");

        campoTextoRestante.setBackground(new java.awt.Color(225, 225, 225));
        campoTextoRestante.setForeground(new java.awt.Color(0, 0, 0));
        campoTextoRestante.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTextoRestante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoRestanteActionPerformed(evt);
            }
        });

        campoTextoFecha.setBackground(new java.awt.Color(225, 225, 225));
        campoTextoFecha.setForeground(new java.awt.Color(0, 0, 0));
        campoTextoFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoTextoParcialidades.setBackground(new java.awt.Color(225, 225, 225));
        campoTextoParcialidades.setForeground(new java.awt.Color(0, 0, 0));
        campoTextoParcialidades.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnRealizarAbono.setBackground(new java.awt.Color(51, 255, 51));
        btnRealizarAbono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRealizarAbono.setForeground(new java.awt.Color(0, 0, 0));
        btnRealizarAbono.setText("Realizar Abono");
        btnRealizarAbono.setBorder(null);
        btnRealizarAbono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRealizarAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarAbonoActionPerformed(evt);
            }
        });

        tblPagos.setBackground(new java.awt.Color(225, 225, 225));
        tblPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Pago", "Fecha", "Estatus", "Abonar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPagos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jblMonto)
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jblRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoTextoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(campoTextoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblParcialidades)
                            .addComponent(campoTextoParcialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRealizarAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblParcialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoParcialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnRealizarAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
      
         frmInicioUsuario adminFrame = new  frmInicioUsuario (beneficiario);
        adminFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void campoTextoRestanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoRestanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoRestanteActionPerformed

    private void btnRealizarAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarAbonoActionPerformed
        JOptionPane.showMessageDialog(null, "Abono Realizado", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRealizarAbonoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarAbono;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField campoTextoFecha;
    private javax.swing.JTextField campoTextoMonto;
    private javax.swing.JTextField campoTextoParcialidades;
    private javax.swing.JTextField campoTextoRestante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblFecha;
    private javax.swing.JLabel jblMonto;
    private javax.swing.JLabel jblParcialidades;
    private javax.swing.JLabel jblRestante;
    private javax.swing.JTable tblPagos;
    // End of variables declaration//GEN-END:variables
}
