/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DTO.BeneficiarioDTO;

/**
 *
 * @author Arturo ITSON
 */
public class frmInicioUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frmInicioUsuario
     */
    
    BeneficiarioDTO beneficiario;
    
    public frmInicioUsuario(BeneficiarioDTO beneficiario) {
        initComponents();
        
        this.beneficiario = beneficiario;
        
         // Agregar ActionListener al botón Administrador
       btnAdministrarCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarCuentasActionPerformed(evt);
            }
        });
         // Agregar ActionListener al botón Administrador
       btnAdministrarAbonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                 btnAdministrarAbonosActionPerformed(evt);
            }
        });
         // Agregar ActionListener al botón Administrador
        btnAdministrarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarPagosActionPerformed(evt);
            }
        });
         // Agregar ActionListener al botón Administrador
       btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
      * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jblBienvenido = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAdministrarPagos = new javax.swing.JButton();
        btnAdministrarAbonos = new javax.swing.JButton();
        btnAdministrarCuentas = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jblBienvenido.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jblBienvenido.setForeground(new java.awt.Color(0, 0, 0));
        jblBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblBienvenido.setText("Bienvenido");

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));

        btnAdministrarPagos.setBackground(new java.awt.Color(23, 154, 249));
        btnAdministrarPagos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdministrarPagos.setForeground(new java.awt.Color(0, 0, 0));
        btnAdministrarPagos.setText("Administrar Pagos");
        btnAdministrarPagos.setBorder(null);
        btnAdministrarPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAdministrarAbonos.setBackground(new java.awt.Color(23, 154, 249));
        btnAdministrarAbonos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdministrarAbonos.setForeground(new java.awt.Color(0, 0, 0));
        btnAdministrarAbonos.setText("Administrar Abonos");
        btnAdministrarAbonos.setBorder(null);
        btnAdministrarAbonos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAdministrarCuentas.setBackground(new java.awt.Color(23, 154, 249));
        btnAdministrarCuentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdministrarCuentas.setForeground(new java.awt.Color(0, 0, 0));
        btnAdministrarCuentas.setText("Administrar Cuentas");
        btnAdministrarCuentas.setBorder(null);
        btnAdministrarCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdministrarCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarCuentasActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(23, 154, 249));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministrarCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministrarAbonos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministrarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnAdministrarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdministrarAbonos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdministrarCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministrarCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarCuentasActionPerformed
    frmAdministrarCuentas cuentas = new  frmAdministrarCuentas();
        cuentas.setVisible(true);
        this.dispose();

        
    }//GEN-LAST:event_btnAdministrarCuentasActionPerformed
private void btnAdministrarAbonosActionPerformed(java.awt.event.ActionEvent evt) {                                                      
frmAdministrarAbonos adminFrame = new  frmAdministrarAbonos(beneficiario);
        adminFrame.setVisible(true);
        this.dispose();

        
    }   
private void btnAdministrarPagosActionPerformed(java.awt.event.ActionEvent evt) {                                                      
frmAdministrarPagos adminFrame = new  frmAdministrarPagos(beneficiario);
        adminFrame.setVisible(true);
        this.dispose();

        
    }   
private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                      
frmIniciarSesion adminFrame = new  frmIniciarSesion();
        adminFrame.setVisible(true);
        this.dispose();

        
    }   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarAbonos;
    private javax.swing.JButton btnAdministrarCuentas;
    private javax.swing.JButton btnAdministrarPagos;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jblBienvenido;
    // End of variables declaration//GEN-END:variables
}
