/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DTO.BeneficiarioDTO;
import DTO.EstatusDTO;
import DTO.PagoDTO;
import DTO.PagoEstatusDTO;
import DTO.PrestamoDTO;
import entidades.BeneficiarioEntidad;
import entidades.EstatusEntidad;
import entidades.PagoEntidad;
import entidades.TipoEntidad;
import excepciones.NegocioException;
import java.util.Date;
import javax.swing.JOptionPane;
import negocio.DatabaseInitializerService;
import negocio.EstatusNegocio;
import negocio.IEstatusNegocio;
import negocio.IPagoEstatusNegocio;
import negocio.IPagoNegocio;
import negocio.IPrestamoNegocio;
import negocio.ITipoNegocio;
import negocio.PagoEstatusNegocio;
import negocio.PagoNegocio;
import negocio.PrestamoNegocio;
import negocio.TipoNegocio;
import utilerias.Convertidor;

/**
 *
 * @author Arturo ITSON
 */
public class frmNuevoPago extends javax.swing.JFrame {

    private IPrestamoNegocio prestamoNegocio = new PrestamoNegocio();
    private IPagoNegocio pagoNegocio = new PagoNegocio();
    private ITipoNegocio tipoNegocio = new TipoNegocio();
    private IPagoEstatusNegocio estatusPago = new PagoEstatusNegocio();
    private IEstatusNegocio estatus = new EstatusNegocio();
    
    private DatabaseInitializerService databaseInitializerService = new DatabaseInitializerService();
    private BeneficiarioDTO beneficiario;
    
    public frmNuevoPago(BeneficiarioDTO beneficiario) {
        this.beneficiario = beneficiario;
        initComponents();
        
        try {
            // Inicializar la base de datos
            databaseInitializerService.initializeDatabase();
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al inicializar la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

  // Inicializa el ComboBox correctamente
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Reembolso", "Proveedor", "Viático"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
    }

// //   private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
//        String tipo = (String) jComboBox1.getSelectedItem();
//        actualizarParcialidades(tipo);
//        actualizarFecha();
//    }

    private void actualizarParcialidades(int tipo) {
        switch (tipo) {
            case 0:
                campoTextoParcialidades.setText("1");
                break;
            case 1:
                campoTextoParcialidades.setText("3");
                break;
            case 2:
                campoTextoParcialidades.setText("7");
                break;
            default:
                campoTextoParcialidades.setText("");
                break;
        }
    }

    private void actualizarFecha() {
        Date date = new Date();
        campoTextoFecha.setText(date.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jblMonto = new javax.swing.JLabel();
        jblFecha = new javax.swing.JLabel();
        jblParcialidades = new javax.swing.JLabel();
        campoTextoMonto = new javax.swing.JTextField();
        campoTextoParcialidades = new javax.swing.JTextField();
        campoTextoFecha = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Pago");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));

        jblMonto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblMonto.setText("Monto");

        jblFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblFecha.setText("Fecha");

        jblParcialidades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblParcialidades.setText("Parcialidades");

        campoTextoParcialidades.setBackground(new java.awt.Color(217, 217, 217));

        campoTextoFecha.setBackground(new java.awt.Color(217, 217, 217));

        btnConfirmar.setBackground(new java.awt.Color(51, 255, 51));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConfirmar.setText("Hecho");
        btnConfirmar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tipo");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reembolso", "Proveedor", "Viático" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblParcialidades)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoTextoParcialidades, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(campoTextoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(campoTextoMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblMonto)
                    .addComponent(campoTextoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblFecha))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblParcialidades)
                    .addComponent(campoTextoParcialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        btnRegresar.setBackground(new java.awt.Color(23, 154, 249));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(349, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(433, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
      try {
            double monto = Double.parseDouble(campoTextoMonto.getText());
            String fecha = campoTextoFecha.getText();
            int parcialidades = Integer.parseInt(campoTextoParcialidades.getText());
            String tipo = (String) jComboBox1.getSelectedItem();

            PrestamoDTO prestamoDTO = new PrestamoDTO(monto, fecha, parcialidades);
            PrestamoDTO prestamoDos;
            prestamoDos = prestamoNegocio.crear(prestamoDTO);
            
            
            
            
            Date date = new Date();
            
            BeneficiarioEntidad beneficario = new BeneficiarioEntidad();
            beneficario.setClaveContrato(beneficiario.getClaveContrato());
            beneficario.setContrasena(beneficiario.getContrasena());
            beneficario.setId(beneficiario.getId());
            beneficario.setMaterno(beneficiario.getMaterno());
            beneficario.setNombres(beneficiario.getNombres());
            beneficario.setPaterno(beneficiario.getPaterno());
            beneficario.setSaldo(beneficiario.getSaldo());
            beneficario.setUsuario(beneficario.getUsuario());
            
            PagoDTO pago = new PagoDTO();
            pago.setBeneficiarioId(beneficario);
            pago.setFechaHora(date);
            pago.setMonto(monto);
            System.out.println(date.toString());
            try{
            TipoEntidad tipo_entidad = new TipoEntidad();
            
            
            
            tipo_entidad.setId(tipoNegocio.obtenerPorId((long) 1).getId());
            tipo_entidad.setNombre(tipoNegocio.obtenerPorId((long) 1 ).getNombre());
            tipo_entidad.setNumeroParcialidades(tipoNegocio.obtenerPorId((long) 1).getNumeroParcialidades());
            
                System.out.println(tipo_entidad.getNombre().toString() + "llll");
                System.out.println(tipo_entidad.getId().toString());
            pago.setTipoId(tipo_entidad);
            }

            catch(NegocioException e){
                System.out.println("error al obtener por id el la entidad tipo");
            }
            
            
            PagoDTO pagoDT = new PagoDTO();
            
            try{
            pagoDT =  pagoNegocio.crear(pago);
                    
                    
                    
            PagoEntidad pa = new PagoEntidad();
            pa.setBeneficiario(pago.getBeneficiarioId());
            pa.setComprobante(pago.getComprobante());
            pa.setFechaHora(pago.getFechaHora());
            pa.setId(pago.getId());
            pa.setMonto(pago.getMonto());
            pa.setTipo(pago.getTipoId());
            
            PagoEstatusDTO pagoEstatusDto = new PagoEstatusDTO();
            pagoEstatusDto.setFechaHora(date);
            pagoEstatusDto.setPagoId(pa);
            EstatusEntidad en = new EstatusEntidad();
            en.setId(estatus.obtenerPorId(((long) 1)).getId());
            en.setNombre(estatus.obtenerPorId(((long) 1)).getNombre());
            
            pagoEstatusDto.setEstatusId(en);
                System.out.println(pagoEstatusDto.getFechaHora().toString() + " fehca aqu");
            pagoEstatusDto.setPagoId(pa);
            estatusPago.crear(pagoEstatusDto, pagoDT, en);
            
                    }
                
                catch(NegocioException e){
                           System.out.println("erroe al guardar el pago");
                        }

            JOptionPane.showMessageDialog(this, "Préstamo guardado exitosamente!");
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar el préstamo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        frmInicioUsuario InicioUsuarioFrame = new frmInicioUsuario(beneficiario);
        InicioUsuarioFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       int tipo = jComboBox1.getSelectedIndex();
        actualizarParcialidades(tipo);
        actualizarFecha();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        int tipo =  jComboBox1.getSelectedIndex();
        actualizarParcialidades(tipo);
        actualizarFecha();
    }//GEN-LAST:event_jComboBox1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField campoTextoFecha;
    private javax.swing.JTextField campoTextoMonto;
    private javax.swing.JTextField campoTextoParcialidades;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jblFecha;
    private javax.swing.JLabel jblMonto;
    private javax.swing.JLabel jblParcialidades;
    // End of variables declaration//GEN-END:variables

}
